/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TypeScript {
        "minify": string;
        "src": string;
    }
}
declare global {
    interface HTMLTypeScriptElement extends Components.TypeScript, HTMLStencilElement {
    }
    var HTMLTypeScriptElement: {
        prototype: HTMLTypeScriptElement;
        new (): HTMLTypeScriptElement;
    };
    interface HTMLElementTagNameMap {
        "type-script": HTMLTypeScriptElement;
    }
}
declare namespace LocalJSX {
    interface TypeScript {
        "minify"?: string;
        "src"?: string;
    }
    interface IntrinsicElements {
        "type-script": TypeScript;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "type-script": LocalJSX.TypeScript & JSXBase.HTMLAttributes<HTMLTypeScriptElement>;
        }
    }
}
